import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Image
          src='https://res.cloudinary.com/dkg7sngv6/image/upload/v1666361828/sample.jpg'
          alt='Picture of a flower'
          width={864}
          height={576}
        />
      </main>
    </div>
  );
}
